spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: a3292588
    username: root

  #rabbitmq:
    #虚拟host 可以不设置,使用server默认host
    #virtual-host: JCcccHost
    #password: guest
    #username: guest
    #port: 5672
    #host: 192.168.211.129


server:
  port: 8084


mybatis:
  mapper-locations: classpath:mapper/*.xml


